baseURL: ""
languageCode: en-us
title: Roland Shield
theme: PaperMod

params:
  mainSections:
  - blog
  - docs
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  profileMode:
    enabled: true # needs to be explicitly set
    title: r0r0 in Cyberville
    subtitle: "Roland Shield embraces the CyberSecOps world with both feet"
    imageUrl: "https://i.imgur.com/ow1tXDy.png"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
       
 # home-info mode
 #homeInfoParams:
 #   Title: "Hi there" # \U0001F44B"
    #Content: Welcome to my blog.
 #  socialIcons: # optional
 #       - name: "LinkedIn"
 #         url: "https://www.linkedin.com/in/rshield/"
 #       - name: "StackOverflow"
 #         url: "https://stackoverflow.com/users/10736875/roland-shield"
markup:
  highlight:
   # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    # noClasses: false
    style: monokai
  goldmark:
    renderer:
      unsafe: true
menu:
  main:
      - identifier: archive
        name: Archive
        url: /archive
        weight: 10
      - identifier: search
        name: Search
        url: /search
        weight: 20        
      - identifier: categories
        name: Categories
        url: /categories
        weight: 30
      - identifier: documents
        name: Documents
        url: /Documents
        weight: 40
      - identifier: tags
        name: Tags
        url: /tags
        weight: 50
      - dentifier: resume
        name: Resume
        url: /resume
        weight: 60
      - identifier: about
        name: About
        url: /about
        weight: 70